default = "v8.15.0"
base = "v8.15.0
install_base = "install_base.sh"
install_file = "install.sh"

[versions]

[versions."v8.15.0"]

config = "1"
options = ["detect"]

[configs]

[configs.1]
install_type = "file"
install = "./install.sh"
install_diff = ""
test = "Gitleaks version"

[options]

detect = "detect --source {source} -r {output} -f sarif"