default = "v8.8.7"
base = "v8.8.7"
install_base = "install_base.sh"
install_file = "install.sh"

[versions]

[versions."v8.8.7"]

config = "1"
options = ["detect"]

[configs]

[configs.1]
install_type = "file"
install = "./install.sh"
install_diff = ""
test = "gitleaks version"

[options]

detect = "git config --global --add safe.directory {source}; {tool} detect --source {source} -r {output} -f sarif"
