default = "v0.34.0"
base = "v0.33.0"
install_base = "install_base.sh"
install_file = "install.sh"

[versions]

[versions."v0.33.0"]

config = "1"
options = ["image"]

[versions."v0.34.0"]

config = "1"
options = ["image"]

[configs]

[configs.1]
install_type = "file"
install = "./install.sh"
install_diff = ""
test = "Trivy --version"

[options]

image = "{tool} image {0} -o {output} -f sarif"
